name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Decode and Create google-services.json
      - name: Decode and Create google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' | base64 --decode > ./android/app/google-services.json

      # Decode and Create firebase.json
      - name: Decode and Create firebase.json
        run: echo '${{ secrets.FIREBASE_JSON }}' | base64 --decode > ./firebase.json

      # Decode and Create firebase_options.dart
      - name: Decode and Create firebase_options.dart
        run: echo '${{ secrets.FIREBASE_OPTIONS }}' | base64 --decode > ./lib/firebase_options.dart

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Build Android Release
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          name: Bookit-${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
