name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Decode Firebase configuration files
      - name: Decode google-services.json
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: 'google-services.json'
          fileDir: './android/app/'
          encodedString: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Decode firebase.json
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: 'firebase.json'
          fileDir: './'
          encodedString: ${{ secrets.FIREBASE_JSON }}

      - name: Decode firebase_options.dart
        uses: timheuer/base64-to-file@v1.2.4
        with:
          fileName: 'firebase_options.dart'
          fileDir: './lib/'
          encodedString: ${{ secrets.FIREBASE_OPTIONS }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Build Android Release
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          name: Bookit-${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
